export const BOOKS_UPDATE_LIST = 'BOOKS_UPDATE_LIST';
export const BOOKS_SET_FETCHING = 'BOOKS_SET_FETCHING';
export const BOOKS_SET_ITEM = 'BOOKS_SET_ITEM';
export const BOOKS_UPDATE_OFFSET = 'BOOKS_UPDATE_OFFSET';
